version: "3"

services:
  webserver:
    build: 
      context: ./bin/php73
    container_name: 'zencart'
    restart: 'always'
    ports:
      - 8081:80
    links: 
      - database
    volumes: 
      #- ./data/app:/var/www/storage
      - ./www:/var/www/html
      - ./config/php/php.ini:/usr/local/etc/php/php.ini
      - ./config/vhosts:/etc/apache2/sites-enabled
      - ./logs/apache2:/var/log/apache2
      - ./logs/xdebug:/var/log/xdebug
      - ./xdebug:/tmp/xdebug
      - ./config/xdebug/php.ini://usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    environment:
      APACHE_DOCUMENT_ROOT: /var/www/html
      MYSQL_ROOT_PASSWORD: testpwd
  database:
    build:
      context: "./bin/mariadb"
    container_name: zencart-database
    restart: 'always'
    volumes: 
      - ./data/mysql:/var/lib/mysql
      - ./logs/mysql:/var/log/mysql
    environment:
      MYSQL_ROOT_PASSWORD: testpwd
      MYSQL_DATABASE: testdb
      MYSQL_USER: testuser
      MYSQL_PASSWORD: randompw
